"""Cart3

Revision ID: 568a762a81a5
Revises: ea0fc97fe5a1
Create Date: 2023-12-03 21:46:50.646668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568a762a81a5'
down_revision: Union[str, None] = 'ea0fc97fe5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('cart_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'cart_id')
    # ### end Alembic commands ###
