"""Cart

Revision ID: 20983d6bae37
Revises: f819b2674217
Create Date: 2023-12-03 21:43:33.842981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20983d6bae37'
down_revision: Union[str, None] = 'f819b2674217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_carts_id'), 'carts', ['id'], unique=False)
    op.drop_constraint('uix_1', 'cart_items', type_='unique')
    op.drop_constraint('cart_items_user_id_fkey', 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cart_items_user_id_fkey', 'cart_items', 'user', ['user_id'], ['id'])
    op.create_unique_constraint('uix_1', 'cart_items', ['user_id', 'product_id'])
    op.drop_index(op.f('ix_carts_id'), table_name='carts')
    op.drop_table('carts')
    # ### end Alembic commands ###
